### ISSUE TITLE
Support exercise nodes

### ISSUE THREAD

**Issue by rgaudin** [openzim/kolibri2zim#37]
Exercise nodes are composed of a single perseus file. A perseus file is a ZIP containing an `exercise.json` entrypoint and other files.

Requires:
- [x] Creating a standalone version of https://github.com/Khan/perseus
- [x] Adding that version to assets of ZIM
- [x] Adding the extracted (or not?) perseus file to the Zim
- [x] Create a *reader* for the exercise: an HTML file calling the perseus code and referencing the perseus file or JSON.

Initial difficulty/step would be to create that standalone version. It should be one or multiple files that work in the browser and don't require any backend.
Might be interesting to look at https://github.com/learningequality/kolibri-exercise-perseus-plugin/ although this can't be reused directly obviously.

Once we have a working offline HTML/CSS/JS reader that can be passed a perseus or JSON file and render it, we can move on an integrate it in kolibri2zim.

**Comment by imnitishng** [comment]
I have been exploring kolibri and the way it handles perseus, I will document my findings here soon.

**Comment by imnitishng** [comment]
Hi @rgaudin sorry this took a lot of time because I ended up looking for solutions in the wrong places
I was able to create a working standalone build for `perseus` using webpack to bundle all the code together and serve it inside of `<script>` tags. This does seem to work fine as per my manual testing but we'll only be sure once this is integrated.
You can have a look at the bundled app [here](https://github.com/imnitishng/standalone-perseus/tree/master).
I will still have to write some functions that change state variables inside perseus to render content correctly, but for that we will need the perseus JSONs from zip files. So I believe integrating this after your feedback would be the next right step and all the perseus changes can be tested and fixed manually once we have more data to test on.
Let me know what you think :smiley:

**Comment by imnitishng** [comment]
Here is a demonstration of the HTML file, the original article from khan academy content is [here](https://www.khanacademy.org/math/cc-fourth-grade-math/imp-measurement-and-data-2/imp-converting-units-of-mass/a/us-customary-units-of-mass-review)
I have cloned 3 parts from the article representing different perseus widgets
![perseus](https://user-images.githubusercontent.com/35267629/120360205-20b77680-c326-11eb-984a-ce12b644ec0f.gif)

**Comment by rgaudin** [comment]
@imnitishng this is great. I've tested it and this is what I was looking for. Thanks again. There are still those debug alerts and errors in the console but those are details we can sort later.

As you mentioned, the next step is probably to look at integration with kolibri2zim.

The source file we get is a perseus file [like this one](https://kolibri-catalog-en.learningequality.org/content/storage/8/7/877bf2feed2f7b012ca304c07f075f04.perseus). I believe the perseus reader is not equiped to deal with such a file so we should extract it in the scraper (it's just a ZIP) and add all the files.

What I don't know is if the reader can deal with the `exercise.json` file which in this example is just a mapping to other JSON files that look like the input you included in your example.

We should also check whether the reader is happy with the content of those JSON, especially the relative-linking parts like

```
![](web+graphie:${☣ LOCALPATH}/images/3a635e3b348ab8755f9a7285d78ea9baabc6d7aa)
```

If this all works directly with your standalone reader, then we can start the integration work.

@imnitishng, can you look into those questions?

**Comment by imnitishng** [comment]
Thank you for checking this out @rgaudin 

> What I don't know is if the reader can deal with the exercise.json file which in this example is just a mapping to other JSON files that look like the input you included in your example.

I have not explored this possibility yet, I will have a look at it and come back to you. Even if it is not supported I think it should not be a challenging task to implement, we could a wrapping JS file that parses the ZIP and serves it accordingly to ZIM. However I will explore if its already supported first.

> We should also check whether the reader is happy with the content of those JSON,

Yes these need to be replaced before they are fed into the reader, kolibri does the same in their perseus plugin, they simply replace the paths to the respective local paths. As mentioned above all this should be done inside the wrapper JS file which we will  include in the HTML.

**Comment by imnitishng** [comment]
Just wanted to give an update on this, I have been working on supporting full perseus files but I realized the standalone reader had many issues rendering exercise content.
- It was only rendering content from perseus articles
- Unable to get render exercises with hints properly
- Unable to submit or interact with the exercises
So I have decided to work on those and finish off the reader. I aim to dispatch a fully functional reader after I have ported all the perseus rendering functionality from showing hints to fetching answers, this did take a lot more time than I expected but the end result would be ready soon. Then we can easily integrate it to `kolibri2zim`.

**Comment by rgaudin** [comment]
Awesome! Thanks @imnitishng for finding that out now and working on fixing it. 👍

**Comment by imnitishng** [comment]
Hi @rgaudin, first of all extremely sorry for abandoning the work for this long, I just got caught up in a lot of stuff (COVID, college). 
So I continued the work on this and fixed most of the issues, now we have a stable standalone perseus renderer. 
I have created a [repository](https://github.com/imnitishng/standalone-perseus-samples) that has many interactive exercises extracted from the `.perseus` ZIP files. 
Essentially a peseus zip file contains all the assets and mapping of the individual questions. There can be ~5-25 or more questions inside a zip file. So what the renderer does is it parses all the data and serves all the questions as a single page application. The user can interact with page to get hints, go to next question, check if the answer is correct or incorrect.

I have tried to replicate the behavior of exercise buttons and alerts that happen in [KA's exercise page](https://www.khanacademy.org/math/cc-2nd-grade-math/cc-2nd-place-value/cc-2nd-skip-counting/e/skip-counting-by-10s)
You can have a look at them, and let me know if there is any feedback. Once done then we can get to integration work.

**Comment by rgaudin** [comment]
Wow thank you @imnitishng !!

I suppose the code is at https://github.com/imnitishng/standalone-perseus/releases/tag/v1.1.3 ?

I have a few stuff to deal with before I can actually look at this in detail but this is great news !

**Comment by imnitishng** [comment]
Thanks! Let me know about the next steps once you get time.
Yes you can find the code on this [branch](https://github.com/imnitishng/standalone-perseus/tree/more_exercises).

**Comment by rgaudin** [comment]
Thank you @imnitishng ; this is great.

Couple of questions:

- I have noticed an expected `assets/perseus` prefix in some of the calls (`assets/perseus/build/1.extra-widgets.js` for instance) that is set in `frame-perseus.js`. I had to remove it to test locally. I suppose this is for in-kolibri usage that you set this, right?
- There are many files in this repo. Could you list which ones are part of the reader and which are from the examples?

Would you be able to describe what is still be to be done to complete the standalone reader and integrate it to kolibri2zim?

My understanding is that the perseus JSON must be available in `#my-data` for the reader to work so I imagine we'd need some code to go from a zipped perseus file, to the live exercise: extract the data obviously, but also parse the JSON and send it to the DOM.

- Is the JSON converted in some way? I noticed copy-pasting (escaping `"`) content from other JSON files is not sufficient.
- Are the `${* LOCALPATH}` URLs resolved by the perseus lib or should we fix those ?

**Comment by imnitishng** [comment]
> I have noticed an expected assets/perseus prefix in some of the calls (assets/perseus/build/1.extra-widgets.js for instance) that is set in frame-perseus.js. I had to remove it to test locally. I suppose this is for in-kolibri usage that you set this, right?

Yes, so this was a hacky way to make the HTML file's relative paths to work inside the zim files from `kolibri2zim`, the `index.html` in standalone-perseus doesn't work because the path is set based on the `assets` folder for zim files. That is why I created the new repo [standalone-perseus-samples](https://github.com/imnitishng/standalone-perseus-samples) to showcase the HTML files only with proper relative paths.

> There are many files in this repo. Could you list which ones are part of the reader and which are from the examples?

I'm guessing you are talking about the [standalone-perseus-samples](https://github.com/imnitishng/standalone-perseus-samples) repo? If so then the files that are responsible for rendering the perseus content are inside [`/assets/perseus`](https://github.com/imnitishng/standalone-perseus-samples/tree/master/assets/perseus), and the [`perseus_exercise`](https://github.com/imnitishng/standalone-perseus-samples/blob/master/perseus_exercise.html) is the HTML template we will use in `kolibri2zim` for rendering exercises. All other folder names that look like hashes contain the SVG and PNG files assets for respective exercises. Apart from this all other HTML files (which are named like hashes) are exercises that will look and work the same when inside a `.zim` file.

If you are talking about the [standalone-perseus](https://github.com/imnitishng/standalone-perseus/tree/more_exercises) then I have already cleaned most of the useless files that served no purpose, and I all the remaining files are required for proper functioning.
`/build` - Contains the full perseus rendering code built using webpack, along with the respective sourcemaps
`/fonts` - Fonts are used to render math content so I just downloaded and placed all the fonts that were missing inside this folder.
`/lib` - Consists of the dependencies used by perseus, (react, mathjax, katex, etc)
`/stylesheets` - Has all the `.less` and `.css` styling for perseus exercises and our HTML template file
`perseus_script.js` - Gets the content from template HTML file and renders it using perseus and also contains the logic for making exercises inside HTML interactive. (checking answer, getting hints)
`solver.js` - Used to solve the exercises automatically(get solution of the exercies), this file currently has no use since 
`index.html` - HTML template, that will be used in `kolibri2zim`


> Would you be able to describe what is still be to be done to complete the standalone reader and integrate it to kolibri2zim?

Since for now we were only focussing on exercise nodes, this task can be marked as done. The reader is able to parse the `.zip` files from the database into different HTML exercises that are interactive as well as follow the same behavior as KA exercises. (I hope you have played around with the HTMLs [here](https://github.com/imnitishng/standalone-perseus-samples)).
Apart from this, KA also has [articles](https://www.khanacademy.org/humanities/ap-art-history/start-here-apah/elements-of-art-apah/a/line) as a content type that utilize perseus for rendering the content, with minor changes that can also be supported using the same renderer. So this can be viewed as a next task before or after the integration of renderer to `kolibri2zim`.

> My understanding is that the perseus JSON must be available in #my-data for the reader to work so I imagine we'd need some code to go from a zipped perseus file, to the live exercise: extract the data obviously, but also parse the JSON and send it to the DOM.

Yes all of this had to be handled before we send the JSON data from `.zip` files to our jinja HTML template.

> Is the JSON converted in some way? I noticed copy-pasting (escaping ") content from other JSON files is not sufficient.
Are the ${* LOCALPATH} URLs resolved by the perseus lib or should we fix those ?

Yes I handled this inside of `scraper.py` for exercise node, I have pushed the code I used to create these HTML files. It encodes JSONs properly and takes care of the `${* LOCALPATH}` by replacing it with the relative paths used in `zim` file.
You can have a look at this version of `kolibri2zim` [on this branch](https://github.com/imnitishng/kolibri2zim/tree/exercise-node-test) (primary changes on `scraper.py` and `get_js_deps.sh`). If you think this is a good starting point then I'll create a PR and we can make changes as required from there.

**Comment by rgaudin** [comment]
Wow, great job!

I think we are ready for you to make a PR from your test branch. I just glanced at the code and did not review it but the feature is there.

For some reason I thought we'd keep the .perseus file and use a [zip.js](https://gildas-lormeau.github.io/zip.js/) or something to read the content but it's not quite possible because the reader accesses the other files via paths. It would require a lot of rewriting of the reader or use service worker to make it work ; either way, that's not interesting.

Regarding the KA articles, we can leave that aside for now.

Congrats!

**Comment by imnitishng** [comment]
Thanks, I'll get on it.
